Add DR filtering matrices
SeisSol/Matrices pull request #10
Opened 2023-10-19 16:17 UTC by krenzland

This PR adds filter matrices for the DR output. Note that the matrices for the quad rule Dunavant is probably incorrect (compare sum of the quad weights for example).

The resample matrix is then a generalization of DR filtering.

2023-11-22 11:56 UTC, sebwolf-de commented
#11 should fix the problems with the Dunavant rule.

2023-11-28 13:40 UTC, krenzland commented
Thanks, I've included the changes. I renamed the quad rules so that the spelling agrees with the matrices already in SeisSol. The current naming includes a space in the file names, which is a bit ugly.

2023-11-30 13:15 UTC, sebwolf-de requested changes

2023-11-30 13:15 UTC, sebwolf-de commented on src/seissol_matrices/dr_matrices.py
> +        V = np.linalg.inv(mass) @ E
Why the inverse, IMHO `solve` is better, because `inv` is less stable.

2023-11-30 14:49 UTC, krenzland commented on src/seissol_matrices/dr_matrices.py
> +        V = np.linalg.inv(mass) @ E
I'm pretty sure it's identical for matrices (mass is diagonal anyway!)

2023-11-30 14:59 UTC, krenzland commented on src/seissol_matrices/dr_matrices.py
> +        V = np.linalg.inv(mass) @ E
Actually it is slightly larger than I expected for very large orders :O

2023-11-30 15:07 UTC, sebwolf-de approved these changes

2023-11-30 15:08 UTC, merged