Add nodal matrices
SeisSol/Matrices pull request #2
Opened 2023-02-16 16:10 UTC by krenzland

Also add pyproject.toml for the build tool poetry.

(Note: It's not ideal that the nodes are hardcoded but that's how it was done for the original matrices as well)

2023-02-16 17:01 UTC, sebwolf-de requested changes
Can you please give a short explanation, what these matrices do in the ReadMe? Please add a new section `Nodal Matrices`.
Rest looks good.

2023-02-16 17:01 UTC, sebwolf-de commented on pyproject.toml
> +authors = ["Your Name <you@example.com>"]
Maybe: "SeisSol Team"?

2023-02-16 17:04 UTC, krenzland commented on pyproject.toml
> +authors = ["Your Name <you@example.com>"]
It's probably better to list people manually - we do not have an email address for the team, right?

2023-02-17 07:49 UTC, sebwolf-de approved these changes

2023-02-17 07:50 UTC, merged